# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Code and Effect  # The site title used as part of the title tag like 'page.title | title'.
tagline: Edmonton Ruby on Rails Web and App Development # A short description used as part of the title tag of the home page like 'title | tagline'.
email: hello@codeandeffect.com
description: Edmonton-based software consultants. We use Ruby on Rails to design and develop web and mobile applications. # Used for the description meta tag and is the fallback for pages that don't provide their own description
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.codeandeffect.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Code and Effect Inc.
logo: code-and-effect-logo.png # URL to a site-wide logo (e.g., /assets/your-company-logo.png)
google_analytics: UA-1478414-49

twitter:
  username: Code_and_Effect
  card: Edmonton-based software consultants. We use Ruby on Rails to design and develop web and mobile applications.

github:
  username: code-and-effect

linkedin:
  username: code-and-effect

social:
  name: Code and Effect
  links:
    - https://twitter.com/code_and_effect
    - https://www.linkedin.com/company/code-and-effect
    - https://github.com/code-and-effect


# Plugin settings
sass:
  sass_dir: _sass # _sass is default
  style: compressed # nested, expanded, compact, or compressed

compress_html:
  clippings: all
  comments: all
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# Build settings
show_excerpts: true
permalink: :title/ # always trailing slashes
plugins:
  - jekyll-gzip
  - jekyll-menus
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - deploy.workflow
  - README.md
